#!/bin/sh
	update-alternatives --remove  passwd passwd.shadow
	update-alternatives --remove  chfn chfn.shadow
	update-alternatives --remove  newgrp newgrp.shadow
	update-alternatives --remove  chsh chsh.shadow
	update-alternatives --remove  groups groups.shadow
	update-alternatives --remove  chpasswd chpasswd.shadow
	update-alternatives --remove  login login.shadow
	update-alternatives --remove  vipw vipw.shadow
	update-alternatives --remove  vigr vigr.shadow
